import type { Stay, StayKind } from "../../types/stay";
import { stay } from "./factory";

type MixStay = {
  name: string;
  company: string;
  zar: number;
  note: string;
  sleeps?: number;
};

function mix(
  slug: string,
  city: string,
  lat: number,
  lng: number,
  hotel: MixStay,
  house: MixStay,
  guest: MixStay,
): Stay[] {
  return [
    stay(
      `stay_${slug}_hotel`,
      hotel.name,
      lat,
      lng,
      hotel.company,
      city,
      "hotel",
      2,
      hotel.zar,
      hotel.note,
    ),
    stay(
      `stay_${slug}_house`,
      house.name,
      lat + 0.008,
      lng + 0.006,
      house.company,
      city,
      "house",
      house.sleeps ?? 6,
      house.zar,
      house.note,
    ),
    stay(
      `stay_${slug}_guest`,
      guest.name,
      lat - 0.006,
      lng + 0.009,
      guest.company,
      city,
      "guesthouse",
      2,
      guest.zar,
      guest.note,
    ),
  ];
}

function extra(
  id: string,
  name: string,
  lat: number,
  lng: number,
  company: string,
  area: string,
  kind: StayKind,
  sleeps: number,
  zar: number,
  note: string,
) {
  return stay(id, name, lat, lng, company, area, kind, sleeps, zar, note);
}

/** Houses, guesthouses, and extra hotels for thin cities. */
export const EXTRA_STAYS: Stay[] = [
  // Cape Town — more houses and guesthouses among the hotels
  extra("stay_ct_fourrosmead", "Four Rosmead", -33.9376, 18.4118, "Four Rosmead", "Gardens, Cape Town", "guesthouse", 2, 1800, "Garden guesthouse on the lower slopes of Table Mountain."),
  extra("stay_ct_derwent", "Derwent House", -33.9328, 18.4074, "Derwent House", "Tamboerskloof, Cape Town", "guesthouse", 2, 1600, "Boutique guesthouse above Kloof Street."),
  extra("stay_ct_africanvilla", "An African Villa", -33.9296, 18.4052, "An African Villa", "Tamboerskloof, Cape Town", "guesthouse", 2, 1200, "Colourful rooms in a converted Victorian house."),
  extra("stay_ct_dewaterkant", "De Waterkant House", -33.9168, 18.4172, "De Waterkant Cottages", "De Waterkant, Cape Town", "house", 6, 3200, "Whole house in the colourful De Waterkant grid."),
  extra("stay_ct_campsbayhouse", "Camps Bay Beach House", -33.9538, 18.3788, "Camps Bay Stays", "Camps Bay, Cape Town", "house", 8, 4800, "Self-catering house a short walk from the beachfront."),
  extra("stay_ct_oranjezicht", "Oranjezicht Family House", -33.9412, 18.4156, "Oranjezicht Stays", "Oranjezicht, Cape Town", "house", 6, 2800, "Mountain-view family house above the City Bowl."),
  extra("stay_ct_bakoven", "Bakoven Sea House", -33.9596, 18.3732, "Bakoven Stays", "Bakoven, Cape Town", "house", 8, 4200, "Atlantic-facing house west of Camps Bay."),
  extra("stay_ct_cadogan", "Cape Cadogan", -33.9304, 18.4096, "Cape Cadogan Boutique Hotel", "Gardens, Cape Town", "hotel", 2, 2400, "Boutique hotel in a heritage Gardens house."),

  // Stellenbosch and Winelands
  extra("stay_stb_majeka", "Majeka House", -33.9624, 18.8506, "Majeka House", "Stellenbosch", "hotel", 2, 2800, "Boutique hotel with a spa on the Stellenbosch edge."),
  extra("stay_stb_ryneveld", "Ryneveld Country Lodge", -33.9386, 18.8624, "Ryneveld Country Lodge", "Stellenbosch", "guesthouse", 2, 1400, "Village guesthouse near the church square."),
  extra("stay_stb_jonkershoek", "Jonkershoek House", -33.9638, 18.9186, "Jonkershoek Stays", "Jonkershoek, Stellenbosch", "house", 8, 2600, "Whole house on the road into the valley."),
  extra("stay_fh_lapetite", "La Petite Ferme", -33.9168, 19.1216, "La Petite Ferme", "Franschhoek", "hotel", 2, 3600, "Hill hotel above the Franschhoek valley."),
  extra("stay_fh_akademie", "Akademie Street Boutique Hotel", -33.9088, 19.1192, "Akademie Street", "Franschhoek", "guesthouse", 2, 2200, "Village rooms on Akademie Street."),
  extra("stay_fh_countryhouse", "Franschhoek Country House", -33.9184, 19.1268, "Franschhoek Country House", "Franschhoek", "house", 6, 3400, "Manor house with a pool in the vines."),
  extra("stay_paarl_pontac", "Pontac Manor", -33.7386, 18.9668, "Pontac Manor Hotel", "Paarl", "hotel", 2, 2100, "Victorian manor hotel in Paarl."),
  extra("stay_paarl_chablis", "Maison Chablis", -33.7422, 18.9784, "Maison Chablis", "Paarl", "guesthouse", 2, 1100, "Garden guesthouse in the Paarl suburbs."),
  extra("stay_paarl_mountain", "Paarl Mountain House", -33.7288, 18.9446, "Paarl Mountain Stays", "Paarl", "house", 6, 1900, "Self-catering house below Paarl Rock."),

  // Johannesburg, Soweto, Pretoria
  extra("stay_jhb_clico", "Clico Boutique Hotel", -26.1448, 28.0412, "Clico Boutique Hotel", "Rosebank, Johannesburg", "hotel", 2, 2400, "Small hotel in a Rosebank garden villa."),
  extra("stay_jhb_tenbompas", "Ten Bompas", -26.1436, 28.0384, "Ten Bompas", "Dunkeld, Johannesburg", "hotel", 2, 3100, "Suite hotel in Dunkeld."),
  extra("stay_jhb_satyagraha", "Satyagraha House", -26.1638, 28.0836, "Satyagraha House", "Orchards, Johannesburg", "guesthouse", 2, 1800, "Heritage guesthouse in Gandhi's former home."),
  extra("stay_jhb_parktown", "Parktown Guesthouse", -26.1786, 28.0342, "Parktown Guesthouse", "Parktown, Johannesburg", "guesthouse", 2, 980, "Ridge guesthouse near the universities."),
  extra("stay_jhb_melville", "Melville House", -26.1752, 28.0086, "Melville Stays", "Melville, Johannesburg", "house", 6, 1600, "Whole house above 7th Street."),
  extra("stay_jhb_parkhurst", "Parkhurst Family House", -26.1408, 28.0176, "Parkhurst Stays", "Parkhurst, Johannesburg", "house", 6, 1800, "Family house near 4th Avenue."),
  extra("stay_jhb_sandtonhouse", "Sandton City House", -26.1088, 28.0522, "Sandton Stays", "Sandton, Johannesburg", "house", 8, 2400, "Self-catering house in the Sandton core."),
  extra("stay_soweto_nthateng", "Nthateng's B&B", -26.2378, 27.9064, "Nthateng's B&B", "Orlando West, Soweto", "guesthouse", 2, 650, "Homestay rooms a short walk from Vilakazi Street."),
  extra("stay_soweto_orlando", "Orlando West House", -26.2392, 27.9106, "Soweto Homestays", "Orlando West, Soweto", "house", 6, 1200, "Whole township house near the museums."),
  extra("stay_pta_brooklyn", "Brooklyn Guesthouse", -25.7716, 28.2368, "Brooklyn Guesthouse", "Brooklyn, Pretoria", "guesthouse", 2, 980, "Suburban guesthouse near Brooklyn Mall."),
  extra("stay_pta_menlo", "Menlo Park House", -25.7664, 28.2562, "Menlo Park Stays", "Menlo Park, Pretoria", "house", 6, 1500, "Family house east of the Union Buildings."),
  extra("stay_pta_foreigners", "Foreigners Boutique Guesthouse", -25.7518, 28.2184, "Foreigners Boutique", "Pretoria", "guesthouse", 2, 1100, "City guesthouse near the diplomatic belt."),

  // Durban and Umhlanga
  extra("stay_dbn_garden", "Garden Court Marine Parade", -29.8572, 31.0368, "Southern Sun", "North Beach, Durban", "hotel", 2, 1500, "Golden Mile hotel facing the promenade."),
  extra("stay_dbn_quarters", "Quarters Hotel Durban", -29.8286, 31.0162, "Quarters Hotels", "Morningside, Durban", "hotel", 2, 1600, "Converted houses on Florida Road."),
  extra("stay_dbn_happyhippo", "Happy Hippo Backpackers", -29.8614, 31.0256, "Happy Hippo", "Durban CBD", "guesthouse", 2, 420, "Beach-city backpacker near the esplanade."),
  extra("stay_dbn_essenwood", "Essenwood House", -29.8326, 31.0124, "Essenwood Stays", "Berea, Durban", "house", 6, 1700, "Ridge house above Florida Road."),
  extra("stay_dbn_north", "Durban North Family House", -29.7784, 31.0386, "Durban North Stays", "Durban North", "house", 8, 1900, "Suburban house near Virginia Bush."),
  extra("stay_dbn_morningside", "Morningside Villa", -29.8272, 31.0188, "Morningside Stays", "Morningside, Durban", "house", 6, 1600, "Whole villa a short walk from Florida Road."),
  extra("stay_umh_pearls", "The Capital Pearls", -29.7268, 31.0824, "The Capital", "Umhlanga", "hotel", 2, 2400, "Apartment-hotel on the Umhlanga ridge."),
  extra("stay_umh_house", "Umhlanga Beach House", -29.7288, 31.0896, "Umhlanga Stays", "Umhlanga", "house", 8, 3200, "Self-catering house near the lighthouse."),
  extra("stay_umh_guest", "Umhlanga Guesthouse", -29.7246, 31.0812, "Umhlanga Guesthouse", "Umhlanga", "guesthouse", 2, 980, "Suburban rooms behind Lagoon Drive."),

  // Eastern Cape cities already started
  extra("stay_gqe_beach", "The Beach Hotel", -33.9796, 25.6648, "The Beach Hotel", "Summerstrand, Gqeberha", "hotel", 2, 1600, "Sea-facing hotel on Marine Drive."),
  extra("stay_gqe_humewood", "Humewood Guesthouse", -33.9748, 25.6486, "Humewood Guesthouse", "Humewood, Gqeberha", "guesthouse", 2, 780, "Beach-suburb rooms near King's Beach."),
  extra("stay_gqe_summerstrand", "Summerstrand Beach House", -33.9864, 25.6722, "Summerstrand Stays", "Summerstrand, Gqeberha", "house", 8, 2100, "Family house behind the beachfront hotels."),
  extra("stay_el_quarry", "The Quarry", -32.9946, 27.8948, "The Quarry Hotel", "East London", "hotel", 2, 1200, "City hotel in a converted quarry."),
  extra("stay_el_gonubie", "Gonubie House", -32.9412, 28.0164, "Gonubie Stays", "Gonubie, East London", "house", 6, 1400, "Coastal house east of the city."),
  extra("stay_el_quigney", "Quigney Guesthouse", -33.0186, 27.9148, "Quigney Guesthouse", "Quigney, East London", "guesthouse", 2, 650, "Rooms near the beachfront and ICC."),
  extra("stay_jbay_diaz", "Diaz 15 Hotel", -34.0486, 24.9218, "Diaz 15", "Jeffreys Bay", "hotel", 2, 1300, "Surf-town hotel near the point."),
  extra("stay_jbay_house", "Supertubes House", -34.0494, 24.9312, "JBay Stays", "Jeffreys Bay", "house", 6, 1800, "Whole house above Supertubes."),

  // Garden Route and Overberg extras
  extra("stay_knysna_stjames", "St James of Knysna", -34.0524, 23.0492, "St James of Knysna", "Knysna", "hotel", 2, 2600, "Lagoon hotel on the Knysna water."),
  extra("stay_knysna_heads", "Knysna Heads House", -34.0786, 23.0608, "Knysna Heads Stays", "The Heads, Knysna", "house", 6, 2800, "House looking over the Knysna Heads."),
  extra("stay_knysna_isola", "Isola Bella", -34.0412, 23.0524, "Isola Bella Guesthouse", "Knysna", "guesthouse", 2, 1100, "Garden guesthouse near the waterfront."),
  extra("stay_plett_grand", "The Grand Cafe and Rooms", -34.0564, 23.3728, "The Grand", "Plettenberg Bay", "hotel", 2, 2800, "Small hotel on the Plett lookout."),
  extra("stay_plett_robberg", "Robberg Beach House", -34.0886, 23.3642, "Robberg Stays", "Plettenberg Bay", "house", 8, 3200, "House near the Robberg peninsula."),
  extra("stay_plett_milkwood", "Milkwood Guesthouse", -34.0548, 23.3684, "Milkwood Guesthouse", "Plettenberg Bay", "guesthouse", 2, 1200, "Town guesthouse a short drive from the beach."),
  extra("stay_hermanus_windsor", "Windsor Hotel", -34.4188, 19.2412, "Windsor Hotel", "Hermanus", "hotel", 2, 1600, "Cliff-path hotel in the old village."),
  extra("stay_hermanus_auberge", "Auberge Burgundy", -34.4192, 19.2456, "Auberge Burgundy", "Hermanus", "guesthouse", 2, 1400, "Village guesthouse near the harbour."),
  extra("stay_hermanus_westcliff", "Westcliff House Hermanus", -34.4164, 19.2386, "Hermanus Stays", "Hermanus", "house", 6, 2200, "Family house above the old harbour."),
  extra("stay_george_protea", "Protea Hotel King George", -33.9684, 22.4628, "Marriott", "George", "hotel", 2, 1400, "City hotel in the George centre."),
  extra("stay_george_hoogekraal", "Hoogekraal Country House", -33.9726, 22.3984, "Hoogekraal", "George", "guesthouse", 2, 1300, "Country guesthouse west of town."),
  extra("stay_george_house", "Outeniqua House", -33.9588, 22.4686, "George Stays", "George", "house", 6, 1600, "Suburban house below the Outeniqua mountains."),
  extra("stay_mossel_point", "The Point Hotel", -34.1836, 22.1584, "The Point Hotel", "Mossel Bay", "hotel", 2, 1500, "Hotel on the rocks at The Point."),
  extra("stay_mossel_diaz", "Diaz Beach House", -34.1688, 22.1086, "Mossel Bay Stays", "Diaz Beach, Mossel Bay", "house", 8, 1900, "Beach house west of the harbour."),
  extra("stay_oudt_riempie", "Protea Hotel Riempie Estate", -33.5986, 22.2084, "Marriott", "Oudtshoorn", "hotel", 2, 1300, "Garden hotel on the edge of town."),
  extra("stay_oudt_meul", "De Oude Meul", -33.5914, 22.1988, "De Oude Meul", "Oudtshoorn", "house", 6, 1400, "Converted mill house in town."),

  extra("stay_bloem_citylodge", "City Lodge Bloemfontein", -29.1148, 26.2164, "City Lodge Hotels", "Bloemfontein", "hotel", 2, 1200, "City hotel near the universities."),
  extra("stay_bloem_westdene", "Westdene House", -29.1074, 26.2082, "Westdene Stays", "Westdene, Bloemfontein", "house", 6, 1300, "Family house in the Westdene grid."),
  extra("stay_mbomb_lodge", "Nelspruit Lodge", -25.4688, 30.9784, "Nelspruit Lodge", "Mbombela", "guesthouse", 2, 980, "Suburban rooms above the CBD."),
  extra("stay_mbomb_sonheuwel", "Sonheuwel House", -25.4624, 30.9726, "Mbombela Stays", "Sonheuwel, Mbombela", "house", 6, 1400, "Family house in the Nelspruit suburbs."),
  extra("stay_wr_house", "White River House", -25.3286, 31.0148, "White River Stays", "White River", "house", 6, 1500, "Garden house near Casterbridge."),
  extra("stay_wr_guest", "White River Guesthouse", -25.3342, 31.0196, "White River Guesthouse", "White River", "guesthouse", 2, 850, "Town guesthouse with a pool."),
  extra("stay_hazy_house", "Sabie River House", -25.0468, 31.1188, "Hazyview Stays", "Hazyview", "house", 8, 1800, "Self-catering house near the Kruger gates."),
  extra("stay_hazy_guest", "Hazyview Guesthouse", -25.0428, 31.1246, "Hazyview Guesthouse", "Hazyview", "guesthouse", 2, 900, "Rooms close to Perry's Bridge."),
  extra("stay_polok_meropa", "Meropa Casino Hotel", -23.9126, 29.4284, "Sun International", "Polokwane", "hotel", 2, 1400, "Hotel at the Meropa complex."),
  extra("stay_polok_house", "Polokwane Family House", -23.9018, 29.4724, "Polokwane Stays", "Polokwane", "house", 6, 1200, "Suburban house east of the CBD."),
  extra("stay_polok_guest", "Polokwane Guesthouse", -23.9084, 29.4568, "Polokwane Guesthouse", "Polokwane", "guesthouse", 2, 720, "Town guesthouse with secure parking."),
  extra("stay_tzaneen_house", "Tzaneen Hill House", -23.8286, 30.1684, "Tzaneen Stays", "Tzaneen", "house", 6, 1300, "House above the town and dam."),
  extra("stay_tzaneen_guest", "Tzaneen Guesthouse", -23.8348, 30.1588, "Tzaneen Guesthouse", "Tzaneen", "guesthouse", 2, 680, "Garden rooms in town."),
  extra("stay_kim_club", "The Kimberley Club", -28.7426, 24.7638, "The Kimberley Club", "Kimberley", "guesthouse", 2, 1100, "Club rooms in the historic diamond city."),
  extra("stay_kim_house", "Kimberley Family House", -28.7324, 24.7586, "Kimberley Stays", "Kimberley", "house", 6, 1200, "Suburban house near the Big Hole."),
  extra("stay_upington_lemust", "Le Must River House", -28.4526, 21.2488, "Le Must", "Upington", "house", 6, 1500, "House on the Orange River."),
  extra("stay_upington_guest", "Upington Guesthouse", -28.4448, 21.2624, "Upington Guesthouse", "Upington", "guesthouse", 2, 720, "Town rooms near the river hotels."),

  // Towns that previously had no listings: hotel, house, and guesthouse
  ...mix("komani", "Komani", -31.897, 26.875, {
    name: "Hexagon Hotel",
    company: "Hexagon Hotel",
    zar: 980,
    note: "Town hotel on the hexagon in Komani.",
  }, {
    name: "Komani Family House",
    company: "Komani Stays",
    zar: 1100,
    note: "Whole suburban house a short drive from the centre.",
  }, {
    name: "Cathcart Road Guesthouse",
    company: "Cathcart Road Guesthouse",
    zar: 620,
    note: "Rooms on the main road through town.",
  }),
  ...mix("ballito", "Ballito", -29.539, 31.214, {
    name: "The Capital Zimbali",
    company: "The Capital",
    zar: 2400,
    note: "Resort hotel next to the Zimbali estate.",
  }, {
    name: "Ballito Hills House",
    company: "Ballito Stays",
    zar: 2800,
    note: "Family house in the Ballito hills above the coast.",
  }, {
    name: "Dolphin Coast Guesthouse",
    company: "Dolphin Coast Guesthouse",
    zar: 980,
    note: "Rooms a short drive from Ballito's beaches.",
  }),
  ...mix("pmb", "Pietermaritzburg", -29.6006, 30.3794, {
    name: "Protea Hotel Hilton Pietermaritzburg",
    company: "Marriott",
    zar: 1400,
    note: "City hotel in the KwaZulu-Natal capital.",
  }, {
    name: "Chase Valley House",
    company: "PMB Stays",
    zar: 1500,
    note: "Suburban house in the northern hills.",
  }, {
    name: "Wutoweg Guesthouse",
    company: "Wutoweg Guesthouse",
    zar: 780,
    note: "Garden guesthouse near the city centre.",
  }),
  ...mix("richardsbay", "Richards Bay", -28.783, 32.0377, {
    name: "The Richards Hotel",
    company: "The Richards",
    zar: 1500,
    note: "City hotel near the harbour and lagoon.",
  }, {
    name: "Meerensee House",
    company: "Richards Bay Stays",
    zar: 1600,
    note: "Family house in Meerensee.",
  }, {
    name: "Alkantstrand Guesthouse",
    company: "Alkantstrand Guesthouse",
    zar: 820,
    note: "Rooms near the main swimming beach.",
  }),
  ...mix("mthatha", "Mthatha", -31.5889, 28.7844, {
    name: "Garden Court Mthatha",
    company: "Southern Sun",
    zar: 1300,
    note: "City hotel in Mthatha.",
  }, {
    name: "Mthatha Family House",
    company: "Mthatha Stays",
    zar: 1100,
    note: "Suburban house close to the N2.",
  }, {
    name: "Mthatha Guesthouse",
    company: "Mthatha Guesthouse",
    zar: 620,
    note: "Town rooms with secure parking.",
  }),
  ...mix("makhanda", "Makhanda", -33.304, 26.523, {
    name: "The Cock House",
    company: "The Cock House",
    zar: 1200,
    note: "Village hotel in a historic High Street house.",
  }, {
    name: "Makhanda House",
    company: "Makhanda Stays",
    zar: 1300,
    note: "Whole house near the universities.",
  }, {
    name: "137 High Street",
    company: "137 High Street",
    zar: 780,
    note: "Guesthouse on the Grahamstown high street.",
  }),
  ...mix("portalfred", "Port Alfred", -33.59, 26.891, {
    name: "Royal St Andrews Hotel",
    company: "Royal St Andrews",
    zar: 1600,
    note: "Hotel beside the Royal Port Alfred golf course.",
  }, {
    name: "Kowie River House",
    company: "Port Alfred Stays",
    zar: 1800,
    note: "House on the Kowie estuary.",
  }, {
    name: "Halyards Guesthouse",
    company: "Halyards",
    zar: 900,
    note: "Rooms near the marina.",
  }),
  ...mix("qonce", "Qonce", -32.88, 27.394, {
    name: "Qonce City Hotel",
    company: "Qonce City Hotel",
    zar: 980,
    note: "Town hotel in King William's Town.",
  }, {
    name: "Qonce Family House",
    company: "Qonce Stays",
    zar: 1000,
    note: "Suburban house near the civic centre.",
  }, {
    name: "Qonce Guesthouse",
    company: "Qonce Guesthouse",
    zar: 560,
    note: "Rooms on the road through town.",
  }),
  ...mix("bhisho", "Bhisho", -32.849, 27.441, {
    name: "Bhisho Hotel",
    company: "Bhisho Hotel",
    zar: 920,
    note: "Hotel near the Eastern Cape government precinct.",
  }, {
    name: "Bhisho House",
    company: "Bhisho Stays",
    zar: 980,
    note: "Family house in the capital.",
  }, {
    name: "Bhisho Guesthouse",
    company: "Bhisho Guesthouse",
    zar: 540,
    note: "Town guesthouse with parking.",
  }),
  ...mix("portshepstone", "Port Shepstone", -30.741, 30.455, {
    name: "Port Shepstone Hotel",
    company: "Port Shepstone Hotel",
    zar: 1100,
    note: "South Coast hotel near the river mouth.",
  }, {
    name: "Umtentweni House",
    company: "South Coast Stays",
    zar: 1400,
    note: "House just north of Port Shepstone.",
  }, {
    name: "Port Shepstone Guesthouse",
    company: "Port Shepstone Guesthouse",
    zar: 680,
    note: "Rooms close to the N2.",
  }),
  ...mix("margate", "Margate", -30.8636, 30.3706, {
    name: "Margate Hotel",
    company: "Margate Hotel",
    zar: 1200,
    note: "Beach hotel on the Lower South Coast.",
  }, {
    name: "Margate Beach House",
    company: "Margate Stays",
    zar: 1700,
    note: "Self-catering house near the main beach.",
  }, {
    name: "Margate Guesthouse",
    company: "Margate Guesthouse",
    zar: 720,
    note: "Suburban rooms a short walk from the strip.",
  }),
  ...mix("howick", "Howick", -29.489, 30.232, {
    name: "Howick Falls Hotel",
    company: "Howick Falls Hotel",
    zar: 1100,
    note: "Hotel near the Howick Falls.",
  }, {
    name: "Midlands House",
    company: "Howick Stays",
    zar: 1500,
    note: "Country house in the KZN Midlands.",
  }, {
    name: "Howick Guesthouse",
    company: "Howick Guesthouse",
    zar: 740,
    note: "Town rooms near the falls and museum.",
  }),
  ...mix("stlucia", "St Lucia", -28.383, 32.417, {
    name: "St Lucia Hotel",
    company: "St Lucia Hotel",
    zar: 1400,
    note: "Village hotel at the iSimangaliso gate.",
  }, {
    name: "St Lucia House",
    company: "St Lucia Stays",
    zar: 1800,
    note: "Self-catering house in the village.",
  }, {
    name: "Elephant Coast Guesthouse",
    company: "Elephant Coast Guesthouse",
    zar: 860,
    note: "Rooms a short walk from the estuary.",
  }),
  ...mix("newcastle", "Newcastle", -27.758, 29.931, {
    name: "Newcastle Hotel",
    company: "Newcastle Hotel",
    zar: 1100,
    note: "Town hotel in northern KwaZulu-Natal.",
  }, {
    name: "Newcastle Family House",
    company: "Newcastle Stays",
    zar: 1200,
    note: "Suburban house below the Drakensberg.",
  }, {
    name: "Newcastle Guesthouse",
    company: "Newcastle Guesthouse",
    zar: 640,
    note: "Rooms near the town centre.",
  }),
  ...mix("ladysmith", "Ladysmith", -28.5597, 29.7778, {
    name: "Royal Hotel Ladysmith",
    company: "Royal Hotel",
    zar: 1000,
    note: "Historic hotel in Ladysmith.",
  }, {
    name: "Ladysmith House",
    company: "Ladysmith Stays",
    zar: 1100,
    note: "Family house near the siege museum.",
  }, {
    name: "Ladysmith Guesthouse",
    company: "Ladysmith Guesthouse",
    zar: 600,
    note: "Town rooms with secure parking.",
  }),
  ...mix("empangeni", "Empangeni", -28.7617, 31.8933, {
    name: "Empangeni Hotel",
    company: "Empangeni Hotel",
    zar: 1100,
    note: "Town hotel inland of Richards Bay.",
  }, {
    name: "Empangeni House",
    company: "Empangeni Stays",
    zar: 1200,
    note: "Suburban house in Empangeni.",
  }, {
    name: "Empangeni Guesthouse",
    company: "Empangeni Guesthouse",
    zar: 620,
    note: "Rooms near the CBD.",
  }),
  ...mix("pinetown", "Pinetown", -29.816, 30.866, {
    name: "Pinetown Hotel",
    company: "Pinetown Hotel",
    zar: 1100,
    note: "Hotel west of Durban in Pinetown.",
  }, {
    name: "Pinetown Family House",
    company: "Pinetown Stays",
    zar: 1300,
    note: "House in the Highway area.",
  }, {
    name: "Pinetown Guesthouse",
    company: "Pinetown Guesthouse",
    zar: 680,
    note: "Suburban rooms near the N3.",
  }),
  ...mix("ulundi", "Ulundi", -28.335, 31.416, {
    name: "Ulundi Hotel",
    company: "Ulundi Hotel",
    zar: 980,
    note: "Town hotel in the historic Zulu capital.",
  }, {
    name: "Ulundi House",
    company: "Ulundi Stays",
    zar: 1000,
    note: "Family house near the museums.",
  }, {
    name: "Ulundi Guesthouse",
    company: "Ulundi Guesthouse",
    zar: 560,
    note: "Rooms in town.",
  }),
  ...mix("worcester", "Worcester", -33.6465, 19.4485, {
    name: "Protea Hotel Worcester",
    company: "Marriott",
    zar: 1200,
    note: "Breede Valley hotel.",
  }, {
    name: "Worcester House",
    company: "Worcester Stays",
    zar: 1300,
    note: "Family house below the Brandwacht mountains.",
  }, {
    name: "Worcester Guesthouse",
    company: "Worcester Guesthouse",
    zar: 700,
    note: "Town rooms near Church Street.",
  }),
  ...mix("beaufortwest", "Beaufort West", -32.3567, 22.583, {
    name: "Oasis Hotel",
    company: "Oasis Hotel",
    zar: 980,
    note: "Karoo hotel on the N1.",
  }, {
    name: "Karoo House",
    company: "Beaufort West Stays",
    zar: 1100,
    note: "Whole house in the Karoo town.",
  }, {
    name: "Beaufort West Guesthouse",
    company: "Beaufort West Guesthouse",
    zar: 580,
    note: "Rooms a short walk from Donkin Street.",
  }),
  ...mix("langebaan", "Langebaan", -33.091, 18.032, {
    name: "The Farmhouse Hotel",
    company: "The Farmhouse Hotel",
    zar: 1800,
    note: "Lagoon hotel on the West Coast.",
  }, {
    name: "Langebaan Beach House",
    company: "Langebaan Stays",
    zar: 2200,
    note: "House facing the Langebaan lagoon.",
  }, {
    name: "Club Mykonos Guesthouse",
    company: "Langebaan Guesthouse",
    zar: 980,
    note: "Rooms near the waterfront.",
  }),
  ...mix("saldanha", "Saldanha", -33.0117, 17.9446, {
    name: "Saldanha Bay Hotel",
    company: "Saldanha Bay Hotel",
    zar: 1300,
    note: "Harbour-town hotel on the West Coast.",
  }, {
    name: "Saldanha House",
    company: "Saldanha Stays",
    zar: 1500,
    note: "Family house above the bay.",
  }, {
    name: "Saldanha Guesthouse",
    company: "Saldanha Guesthouse",
    zar: 720,
    note: "Town rooms near the waterfront.",
  }),
  ...mix("swellendam", "Swellendam", -34.0226, 20.4417, {
    name: "Swellengrebel Hotel",
    company: "Swellengrebel Hotel",
    zar: 1300,
    note: "Village hotel below the Langeberg.",
  }, {
    name: "Swellendam House",
    company: "Swellendam Stays",
    zar: 1600,
    note: "Cape house in the historic village.",
  }, {
    name: "De Kloof Guesthouse",
    company: "De Kloof",
    zar: 900,
    note: "Garden guesthouse in Swellendam.",
  }),
  ...mix("simonstown", "Simon's Town", -34.1936, 18.4328, {
    name: "The Boulders Beach Hotel",
    company: "Boulders Beach Hotel",
    zar: 1800,
    note: "Hotel near the penguin colony.",
  }, {
    name: "Simon's Town Harbour House",
    company: "Simon's Town Stays",
    zar: 2400,
    note: "Whole house above the naval harbour.",
  }, {
    name: "British Hotel Apartments",
    company: "British Hotel",
    zar: 1100,
    note: "Historic guesthouse rooms on St George's Street.",
  }),
  ...mix("centurion", "Centurion", -25.8603, 28.1894, {
    name: "Centurion Lake Hotel",
    company: "Centurion Lake Hotel",
    zar: 1400,
    note: "Hotel beside Centurion Lake.",
  }, {
    name: "Centurion Family House",
    company: "Centurion Stays",
    zar: 1600,
    note: "Suburban house near the Gautrain.",
  }, {
    name: "Centurion Guesthouse",
    company: "Centurion Guesthouse",
    zar: 820,
    note: "Rooms in the Centurion suburbs.",
  }),
  ...mix("midrand", "Midrand", -25.975, 28.128, {
    name: "Midrand Hotel",
    company: "Midrand Hotel",
    zar: 1300,
    note: "Business hotel between Johannesburg and Pretoria.",
  }, {
    name: "Midrand House",
    company: "Midrand Stays",
    zar: 1500,
    note: "Family house in a Midrand estate.",
  }, {
    name: "Midrand Guesthouse",
    company: "Midrand Guesthouse",
    zar: 780,
    note: "Rooms near the N1.",
  }),
  ...mix("randburg", "Randburg", -26.0936, 28.0064, {
    name: "Randburg Hotel",
    company: "Randburg Hotel",
    zar: 1200,
    note: "North Johannesburg hotel.",
  }, {
    name: "Randburg House",
    company: "Randburg Stays",
    zar: 1400,
    note: "Suburban house near the civic centre.",
  }, {
    name: "Randburg Guesthouse",
    company: "Randburg Guesthouse",
    zar: 720,
    note: "Rooms in the Randburg suburbs.",
  }),
  ...mix("roodepoort", "Roodepoort", -26.1625, 27.8725, {
    name: "Roodepoort Hotel",
    company: "Roodepoort Hotel",
    zar: 1100,
    note: "West Rand hotel.",
  }, {
    name: "Roodepoort House",
    company: "Roodepoort Stays",
    zar: 1300,
    note: "Family house near Clearwater.",
  }, {
    name: "Roodepoort Guesthouse",
    company: "Roodepoort Guesthouse",
    zar: 680,
    note: "Suburban rooms on the West Rand.",
  }),
  ...mix("krugersdorp", "Krugersdorp", -26.1, 27.767, {
    name: "Krugersdorp Hotel",
    company: "Krugersdorp Hotel",
    zar: 1100,
    note: "Town hotel near the Cradle of Humankind.",
  }, {
    name: "Krugersdorp House",
    company: "Krugersdorp Stays",
    zar: 1300,
    note: "Family house on the West Rand.",
  }, {
    name: "Krugersdorp Guesthouse",
    company: "Krugersdorp Guesthouse",
    zar: 660,
    note: "Town rooms with parking.",
  }),
  ...mix("benoni", "Benoni", -26.1886, 28.3208, {
    name: "Lakes Hotel Benoni",
    company: "Lakes Hotel",
    zar: 1200,
    note: "East Rand hotel by the lakes.",
  }, {
    name: "Benoni House",
    company: "Benoni Stays",
    zar: 1300,
    note: "Suburban house in Benoni.",
  }, {
    name: "Benoni Guesthouse",
    company: "Benoni Guesthouse",
    zar: 680,
    note: "Rooms near the town centre.",
  }),
  ...mix("boksburg", "Boksburg", -26.225, 28.25, {
    name: "Boksburg Hotel",
    company: "Boksburg Hotel",
    zar: 1100,
    note: "East Rand hotel near OR Tambo.",
  }, {
    name: "Boksburg House",
    company: "Boksburg Stays",
    zar: 1300,
    note: "Family house in Boksburg.",
  }, {
    name: "Boksburg Guesthouse",
    company: "Boksburg Guesthouse",
    zar: 660,
    note: "Rooms a short drive from the airport.",
  }),
  ...mix("germiston", "Germiston", -26.217, 28.167, {
    name: "Germiston Hotel",
    company: "Germiston Hotel",
    zar: 1100,
    note: "East Rand hotel in Germiston.",
  }, {
    name: "Germiston House",
    company: "Germiston Stays",
    zar: 1200,
    note: "Suburban house near the lake.",
  }, {
    name: "Germiston Guesthouse",
    company: "Germiston Guesthouse",
    zar: 640,
    note: "Town rooms with secure parking.",
  }),
  ...mix("alberton", "Alberton", -26.267, 28.122, {
    name: "Alberton Hotel",
    company: "Alberton Hotel",
    zar: 1100,
    note: "South Johannesburg hotel.",
  }, {
    name: "Alberton House",
    company: "Alberton Stays",
    zar: 1300,
    note: "Family house in Alberton.",
  }, {
    name: "Alberton Guesthouse",
    company: "Alberton Guesthouse",
    zar: 660,
    note: "Suburban rooms near the N3.",
  }),
  ...mix("springs", "Springs", -26.25, 28.4, {
    name: "Springs Hotel",
    company: "Springs Hotel",
    zar: 1000,
    note: "East Rand town hotel.",
  }, {
    name: "Springs House",
    company: "Springs Stays",
    zar: 1100,
    note: "Suburban house in Springs.",
  }, {
    name: "Springs Guesthouse",
    company: "Springs Guesthouse",
    zar: 600,
    note: "Town rooms.",
  }),
  ...mix("vereeniging", "Vereeniging", -26.6731, 27.9261, {
    name: "Vereeniging Hotel",
    company: "Vereeniging Hotel",
    zar: 1100,
    note: "Vaal hotel in Vereeniging.",
  }, {
    name: "Vaal House",
    company: "Vereeniging Stays",
    zar: 1300,
    note: "House near the Vaal River.",
  }, {
    name: "Vereeniging Guesthouse",
    company: "Vereeniging Guesthouse",
    zar: 640,
    note: "Town rooms.",
  }),
  ...mix("vanderbijlpark", "Vanderbijlpark", -26.7117, 27.838, {
    name: "Riviera on Vaal",
    company: "Riviera on Vaal",
    zar: 1400,
    note: "Hotel and golf estate on the Vaal.",
  }, {
    name: "Vanderbijlpark House",
    company: "Vaal Stays",
    zar: 1300,
    note: "Suburban house near the river.",
  }, {
    name: "Vanderbijlpark Guesthouse",
    company: "Vanderbijlpark Guesthouse",
    zar: 680,
    note: "Rooms in the Vaal town.",
  }),
  ...mix("welkom", "Welkom", -27.983, 26.733, {
    name: "Welkom Inn",
    company: "Welkom Inn",
    zar: 980,
    note: "Goldfields hotel in Welkom.",
  }, {
    name: "Welkom House",
    company: "Welkom Stays",
    zar: 1100,
    note: "Suburban house in the Goldfields.",
  }, {
    name: "Welkom Guesthouse",
    company: "Welkom Guesthouse",
    zar: 560,
    note: "Town rooms.",
  }),
  ...mix("bethlehem", "Bethlehem", -28.23, 28.307, {
    name: "Bethlehem Hotel",
    company: "Bethlehem Hotel",
    zar: 1000,
    note: "Eastern Free State hotel.",
  }, {
    name: "Bethlehem House",
    company: "Bethlehem Stays",
    zar: 1100,
    note: "Family house below the Maluti foothills.",
  }, {
    name: "Bethlehem Guesthouse",
    company: "Bethlehem Guesthouse",
    zar: 580,
    note: "Town rooms.",
  }),
  ...mix("kroonstad", "Kroonstad", -27.65, 27.234, {
    name: "Kroonstad Hotel",
    company: "Kroonstad Hotel",
    zar: 980,
    note: "N1 hotel in Kroonstad.",
  }, {
    name: "Kroonstad House",
    company: "Kroonstad Stays",
    zar: 1000,
    note: "Suburban house in town.",
  }, {
    name: "Kroonstad Guesthouse",
    company: "Kroonstad Guesthouse",
    zar: 540,
    note: "Rooms near the centre.",
  }),
  ...mix("sasolburg", "Sasolburg", -26.813, 27.817, {
    name: "Sasolburg Hotel",
    company: "Sasolburg Hotel",
    zar: 1000,
    note: "Vaal hotel in Sasolburg.",
  }, {
    name: "Sasolburg House",
    company: "Sasolburg Stays",
    zar: 1100,
    note: "Family house in Sasolburg.",
  }, {
    name: "Sasolburg Guesthouse",
    company: "Sasolburg Guesthouse",
    zar: 560,
    note: "Town rooms.",
  }),
  ...mix("parys", "Parys", -26.903, 27.457, {
    name: "Parys Vale Hotel",
    company: "Parys Vale",
    zar: 1300,
    note: "Vaal-river hotel in Parys.",
  }, {
    name: "Parys River House",
    company: "Parys Stays",
    zar: 1600,
    note: "House near the Vaal adventure stretch.",
  }, {
    name: "Parys Guesthouse",
    company: "Parys Guesthouse",
    zar: 780,
    note: "Village rooms near the antique shops.",
  }),
  ...mix("harrismith", "Harrismith", -28.273, 29.129, {
    name: "Harrismith Inn",
    company: "Harrismith Inn",
    zar: 1100,
    note: "N3 hotel at the Drakensberg gateway.",
  }, {
    name: "Harrismith House",
    company: "Harrismith Stays",
    zar: 1200,
    note: "Family house in Harrismith.",
  }, {
    name: "Harrismith Guesthouse",
    company: "Harrismith Guesthouse",
    zar: 620,
    note: "Town rooms near the N3.",
  }),
  ...mix("qwaqwa", "QwaQwa", -28.5389, 28.8158, {
    name: "Phuthaditjhaba Hotel",
    company: "Phuthaditjhaba Hotel",
    zar: 980,
    note: "Town hotel in QwaQwa.",
  }, {
    name: "QwaQwa House",
    company: "QwaQwa Stays",
    zar: 1100,
    note: "Family house below the Sentinel.",
  }, {
    name: "QwaQwa Guesthouse",
    company: "QwaQwa Guesthouse",
    zar: 560,
    note: "Rooms in Phuthaditjhaba.",
  }),
  ...mix("graskop", "Graskop", -24.931, 30.843, {
    name: "Graskop Hotel",
    company: "Graskop Hotel",
    zar: 1400,
    note: "Panorama-route hotel in the village.",
  }, {
    name: "Graskop House",
    company: "Graskop Stays",
    zar: 1600,
    note: "Self-catering house near God's Window.",
  }, {
    name: "Graskop Guesthouse",
    company: "Graskop Guesthouse",
    zar: 820,
    note: "Village rooms on the Panorama Route.",
  }),
  ...mix("sabie", "Sabie", -25.099, 30.78, {
    name: "Floreat River Lodge",
    company: "Floreat",
    zar: 1300,
    note: "Sabie hotel on the river.",
  }, {
    name: "Sabie Forest House",
    company: "Sabie Stays",
    zar: 1500,
    note: "House in the forestry town.",
  }, {
    name: "Sabie Guesthouse",
    company: "Sabie Guesthouse",
    zar: 780,
    note: "Town rooms near the waterfalls.",
  }),
  ...mix("barberton", "Barberton", -25.788, 31.053, {
    name: "Barberton Hotel",
    company: "Barberton Hotel",
    zar: 1100,
    note: "Lowveld hotel in the historic mining town.",
  }, {
    name: "Barberton House",
    company: "Barberton Stays",
    zar: 1200,
    note: "Family house in Barberton.",
  }, {
    name: "Barberton Guesthouse",
    company: "Barberton Guesthouse",
    zar: 640,
    note: "Town rooms.",
  }),
  ...mix("malelane", "Malelane", -25.49, 31.517, {
    name: "Malelane Hotel",
    company: "Malelane Hotel",
    zar: 1400,
    note: "Hotel near the Kruger Malelane gate.",
  }, {
    name: "Crocodile River House",
    company: "Malelane Stays",
    zar: 1800,
    note: "House near the river and park gate.",
  }, {
    name: "Malelane Guesthouse",
    company: "Malelane Guesthouse",
    zar: 860,
    note: "Rooms close to the N4.",
  }),
  ...mix("emalahleni", "eMalahleni", -25.873, 29.233, {
    name: "eMalahleni Hotel",
    company: "eMalahleni Hotel",
    zar: 1100,
    note: "Highveld hotel in Witbank.",
  }, {
    name: "eMalahleni House",
    company: "eMalahleni Stays",
    zar: 1200,
    note: "Suburban house in eMalahleni.",
  }, {
    name: "eMalahleni Guesthouse",
    company: "eMalahleni Guesthouse",
    zar: 620,
    note: "Town rooms.",
  }),
  ...mix("middelburg", "Middelburg", -25.775, 29.464, {
    name: "Middelburg Hotel",
    company: "Middelburg Hotel",
    zar: 1100,
    note: "N4 hotel in Middelburg.",
  }, {
    name: "Middelburg House",
    company: "Middelburg Stays",
    zar: 1200,
    note: "Family house in Middelburg.",
  }, {
    name: "Middelburg Guesthouse",
    company: "Middelburg Guesthouse",
    zar: 620,
    note: "Town rooms.",
  }),
  ...mix("secunda", "Secunda", -26.55, 29.167, {
    name: "Secunda Hotel",
    company: "Secunda Hotel",
    zar: 1100,
    note: "Mpumalanga hotel in Secunda.",
  }, {
    name: "Secunda House",
    company: "Secunda Stays",
    zar: 1200,
    note: "Suburban house in Secunda.",
  }, {
    name: "Secunda Guesthouse",
    company: "Secunda Guesthouse",
    zar: 600,
    note: "Town rooms.",
  }),
  ...mix("ermelo", "Ermelo", -26.533, 29.983, {
    name: "Ermelo Hotel",
    company: "Ermelo Hotel",
    zar: 1000,
    note: "Highveld hotel on the N11.",
  }, {
    name: "Ermelo House",
    company: "Ermelo Stays",
    zar: 1100,
    note: "Family house in Ermelo.",
  }, {
    name: "Ermelo Guesthouse",
    company: "Ermelo Guesthouse",
    zar: 560,
    note: "Town rooms.",
  }),
  ...mix("lydenburg", "Mashishing", -25.096, 30.446, {
    name: "Lydenburg Hotel",
    company: "Lydenburg Hotel",
    zar: 1100,
    note: "Hotel in Mashishing on the Panorama road.",
  }, {
    name: "Mashishing House",
    company: "Lydenburg Stays",
    zar: 1200,
    note: "House in the old Lydenburg town.",
  }, {
    name: "Lydenburg Guesthouse",
    company: "Lydenburg Guesthouse",
    zar: 640,
    note: "Town rooms.",
  }),
  ...mix("standerton", "Standerton", -26.933, 29.233, {
    name: "Standerton Hotel",
    company: "Standerton Hotel",
    zar: 980,
    note: "Vaal hotel in Standerton.",
  }, {
    name: "Standerton House",
    company: "Standerton Stays",
    zar: 1100,
    note: "Family house in Standerton.",
  }, {
    name: "Standerton Guesthouse",
    company: "Standerton Guesthouse",
    zar: 540,
    note: "Town rooms.",
  }),
  ...mix("potchefstroom", "Potchefstroom", -26.715, 27.096, {
    name: "Potchefstroom Hotel",
    company: "Potchefstroom Hotel",
    zar: 1200,
    note: "University-town hotel.",
  }, {
    name: "Potch House",
    company: "Potchefstroom Stays",
    zar: 1300,
    note: "Family house near the campus.",
  }, {
    name: "Potchefstroom Guesthouse",
    company: "Potchefstroom Guesthouse",
    zar: 700,
    note: "Suburban rooms.",
  }),
  ...mix("klerksdorp", "Klerksdorp", -26.852, 26.667, {
    name: "Klerksdorp Hotel",
    company: "Klerksdorp Hotel",
    zar: 1100,
    note: "City hotel in the Matlosana area.",
  }, {
    name: "Klerksdorp House",
    company: "Klerksdorp Stays",
    zar: 1200,
    note: "Suburban house in Klerksdorp.",
  }, {
    name: "Klerksdorp Guesthouse",
    company: "Klerksdorp Guesthouse",
    zar: 620,
    note: "Town rooms.",
  }),
  ...mix("brits", "Brits", -25.633, 27.783, {
    name: "Brits Hotel",
    company: "Brits Hotel",
    zar: 1100,
    note: "Hotel between Pretoria and the Magaliesberg.",
  }, {
    name: "Brits House",
    company: "Brits Stays",
    zar: 1200,
    note: "Family house in Brits.",
  }, {
    name: "Brits Guesthouse",
    company: "Brits Guesthouse",
    zar: 640,
    note: "Town rooms.",
  }),
  ...mix("mahikeng", "Mahikeng", -25.865, 25.644, {
    name: "Mahikeng Hotel",
    company: "Mahikeng Hotel",
    zar: 1100,
    note: "Hotel in the North West capital.",
  }, {
    name: "Mahikeng House",
    company: "Mahikeng Stays",
    zar: 1200,
    note: "Suburban house in Mmabatho.",
  }, {
    name: "Mahikeng Guesthouse",
    company: "Mahikeng Guesthouse",
    zar: 620,
    note: "Town rooms.",
  }),
  ...mix("vryburg", "Vryburg", -26.958, 24.73, {
    name: "Vryburg Hotel",
    company: "Vryburg Hotel",
    zar: 980,
    note: "Cattle-country hotel in Vryburg.",
  }, {
    name: "Vryburg House",
    company: "Vryburg Stays",
    zar: 1000,
    note: "Family house in Vryburg.",
  }, {
    name: "Vryburg Guesthouse",
    company: "Vryburg Guesthouse",
    zar: 540,
    note: "Town rooms.",
  }),
  ...mix("rustenburg", "Rustenburg", -25.667, 27.242, {
    name: "Rustenburg Hotel",
    company: "Rustenburg Hotel",
    zar: 1300,
    note: "City hotel near the Magaliesberg.",
  }, {
    name: "Rustenburg House",
    company: "Rustenburg Stays",
    zar: 1400,
    note: "Suburban house in Rustenburg.",
  }, {
    name: "Rustenburg Guesthouse",
    company: "Rustenburg Guesthouse",
    zar: 720,
    note: "Town rooms on the way to Sun City.",
  }),
  ...mix("thohoyandou", "Thohoyandou", -22.967, 30.484, {
    name: "Thohoyandou Hotel",
    company: "Thohoyandou Hotel",
    zar: 1100,
    note: "Hotel in the Vhembe capital.",
  }, {
    name: "Thohoyandou House",
    company: "Thohoyandou Stays",
    zar: 1200,
    note: "Family house in Thohoyandou.",
  }, {
    name: "Thohoyandou Guesthouse",
    company: "Thohoyandou Guesthouse",
    zar: 600,
    note: "Town rooms.",
  }),
  ...mix("musina", "Musina", -22.348, 30.04, {
    name: "Musina Hotel",
    company: "Musina Hotel",
    zar: 1100,
    note: "Border hotel near Beitbridge.",
  }, {
    name: "Musina House",
    company: "Musina Stays",
    zar: 1200,
    note: "Suburban house in Musina.",
  }, {
    name: "Musina Guesthouse",
    company: "Musina Guesthouse",
    zar: 620,
    note: "Town rooms on the N1.",
  }),
  ...mix("mokopane", "Mokopane", -24.194, 29.009, {
    name: "Mokopane Hotel",
    company: "Mokopane Hotel",
    zar: 1100,
    note: "N1 hotel in Mokopane.",
  }, {
    name: "Mokopane House",
    company: "Mokopane Stays",
    zar: 1200,
    note: "Family house in town.",
  }, {
    name: "Mokopane Guesthouse",
    company: "Mokopane Guesthouse",
    zar: 620,
    note: "Town rooms.",
  }),
  ...mix("makhado", "Makhado", -23.05, 29.903, {
    name: "Makhado Hotel",
    company: "Makhado Hotel",
    zar: 1100,
    note: "Soutpansberg hotel in Louis Trichardt.",
  }, {
    name: "Makhado House",
    company: "Makhado Stays",
    zar: 1200,
    note: "Family house below the Soutpansberg.",
  }, {
    name: "Makhado Guesthouse",
    company: "Makhado Guesthouse",
    zar: 640,
    note: "Town rooms.",
  }),
  ...mix("belabela", "Bela-Bela", -24.885, 28.294, {
    name: "Bela-Bela Hotel",
    company: "Bela-Bela Hotel",
    zar: 1300,
    note: "Warmbaths hotel in Bela-Bela.",
  }, {
    name: "Bela-Bela House",
    company: "Bela-Bela Stays",
    zar: 1500,
    note: "Family house near the hot springs.",
  }, {
    name: "Bela-Bela Guesthouse",
    company: "Bela-Bela Guesthouse",
    zar: 780,
    note: "Town rooms.",
  }),
  ...mix("lephalale", "Lephalale", -23.674, 27.745, {
    name: "Lephalale Hotel",
    company: "Lephalale Hotel",
    zar: 1200,
    note: "Bushveld hotel in Lephalale.",
  }, {
    name: "Lephalale House",
    company: "Lephalale Stays",
    zar: 1300,
    note: "Suburban house in Ellisras.",
  }, {
    name: "Lephalale Guesthouse",
    company: "Lephalale Guesthouse",
    zar: 680,
    note: "Town rooms.",
  }),
  ...mix("giyani", "Giyani", -23.302, 30.716, {
    name: "Giyani Hotel",
    company: "Giyani Hotel",
    zar: 1000,
    note: "Town hotel in Giyani.",
  }, {
    name: "Giyani House",
    company: "Giyani Stays",
    zar: 1100,
    note: "Family house in Giyani.",
  }, {
    name: "Giyani Guesthouse",
    company: "Giyani Guesthouse",
    zar: 560,
    note: "Town rooms.",
  }),
  ...mix("hoedspruit", "Hoedspruit", -24.351, 30.951, {
    name: "Hoedspruit Hotel",
    company: "Hoedspruit Hotel",
    zar: 1500,
    note: "Lowveld hotel near the Kruger Orpen road.",
  }, {
    name: "Hoedspruit Bush House",
    company: "Hoedspruit Stays",
    zar: 2200,
    note: "Self-catering house on a wildlife estate.",
  }, {
    name: "Hoedspruit Guesthouse",
    company: "Hoedspruit Guesthouse",
    zar: 900,
    note: "Town rooms near the airport.",
  }),
  ...mix("phalaborwa", "Phalaborwa", -23.943, 31.141, {
    name: "Phalaborwa Hotel",
    company: "Phalaborwa Hotel",
    zar: 1300,
    note: "Hotel at the Kruger Phalaborwa gate.",
  }, {
    name: "Phalaborwa House",
    company: "Phalaborwa Stays",
    zar: 1600,
    note: "Suburban house near the park gate.",
  }, {
    name: "Phalaborwa Guesthouse",
    company: "Phalaborwa Guesthouse",
    zar: 780,
    note: "Town rooms.",
  }),
  ...mix("kuruman", "Kuruman", -27.452, 23.433, {
    name: "Kuruman Hotel",
    company: "Kuruman Hotel",
    zar: 1000,
    note: "Kalahari hotel near the Eye of Kuruman.",
  }, {
    name: "Kuruman House",
    company: "Kuruman Stays",
    zar: 1100,
    note: "Family house in Kuruman.",
  }, {
    name: "Kuruman Guesthouse",
    company: "Kuruman Guesthouse",
    zar: 560,
    note: "Town rooms.",
  }),
  ...mix("deaar", "De Aar", -30.65, 24.012, {
    name: "De Aar Hotel",
    company: "De Aar Hotel",
    zar: 920,
    note: "Karoo railway-town hotel.",
  }, {
    name: "De Aar House",
    company: "De Aar Stays",
    zar: 1000,
    note: "Family house in De Aar.",
  }, {
    name: "De Aar Guesthouse",
    company: "De Aar Guesthouse",
    zar: 520,
    note: "Town rooms.",
  }),
  ...mix("kathu", "Kathu", -27.695, 23.049, {
    name: "Kathu Hotel",
    company: "Kathu Hotel",
    zar: 1200,
    note: "Kalahari hotel in the mining town.",
  }, {
    name: "Kathu House",
    company: "Kathu Stays",
    zar: 1300,
    note: "Suburban house in Kathu.",
  }, {
    name: "Kathu Guesthouse",
    company: "Kathu Guesthouse",
    zar: 680,
    note: "Town rooms.",
  }),
  ...mix("springbok", "Springbok", -29.664, 17.886, {
    name: "Springbok Hotel",
    company: "Springbok Hotel",
    zar: 1100,
    note: "Namaqualand hotel in Springbok.",
  }, {
    name: "Springbok House",
    company: "Springbok Stays",
    zar: 1200,
    note: "Family house in town.",
  }, {
    name: "Springbok Guesthouse",
    company: "Springbok Guesthouse",
    zar: 640,
    note: "Town rooms near the N7.",
  }),
];
